title: Apple Gradient
logo: "images/logo.svg" # You can add own logo image.
description: Tech blog about all things Apple
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://applegradient.com" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Daniel Yang

# Hero Section
hero: false # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Raked Minimalistic Theme # Add your hero title
hero-subtitle: For those who love simplicity # Add your hero subtitle
hero-image: images/14.jpg # Add background image in section hero

# Footer
footer-image: images/footergradient.png # Add background image in footer

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
